apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: flexcars-cluster
  region: eu-west-3

vpc:
  cidr: "192.168.0.0/16"
  subnets:
    public:
      eu-west-3a: { cidr: "192.168.1.0/24" }
      eu-west-3b: { cidr: "192.168.2.0/24" }
    private:
      eu-west-3a: { cidr: "192.168.3.0/24" }
      eu-west-3b: { cidr: "192.168.4.0/24" }

nodeGroups:
  - name: flexcars-public-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ssh:
      allow: true
  - name: flexcars-private-workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true
    ssh:
      allow: true
