-- AlterTable
ALTER TABLE "CarSitter" ALTER COLUMN "currentLocationLat" DROP NOT NULL,
ALTER COLUMN "currentLocationLng" DROP NOT NULL,
ALTER COLUMN "availability" SET DEFAULT 'BUSY',
ALTER COLUMN "lastActiveAt" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Document" ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "fileUrl" DROP NOT NULL,
ALTER COLUMN "verified" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Incident" ALTER COLUMN "severity" DROP NOT NULL,
ALTER COLUMN "photosUrl" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'OPEN';

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "invoiceNumber" DROP NOT NULL,
ALTER COLUMN "amount" DROP NOT NULL,
ALTER COLUMN "dueDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "paidAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'UNPAID';

-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "type" SET DEFAULT 'EMAIL',
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "message" DROP NOT NULL,
ALTER COLUMN "sentAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isRead" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "method" SET DEFAULT 'STRIPE',
ALTER COLUMN "transactionId" DROP NOT NULL,
ALTER COLUMN "paidAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "PricingRule" ALTER COLUMN "durationType" SET DEFAULT 'HOURLY',
ALTER COLUMN "basePrice" DROP NOT NULL,
ALTER COLUMN "dynamicMultiplier" DROP NOT NULL;

-- AlterTable
ALTER TABLE "RentalContract" ALTER COLUMN "pdfUrl" DROP NOT NULL,
ALTER COLUMN "signedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "VehicleRecommendation" ALTER COLUMN "score" DROP NOT NULL,
ALTER COLUMN "reason" DROP NOT NULL;
